name: CML & DVC Holiday Package Prediction
on: [push]
jobs:
  train-and-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '16'   
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: iterative/setup-cml@v1
      - uses: iterative/setup-dvc@v1
        with:
          version: '3.7.0'
      - name: Train model
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          dvc pull data
          pip install -r requirements.txt
          dvc repro
      - name: Create CML report
        run: |
          # Compare metrics to main
          #test $(git branch --show-current) == main || git fetch --depth=1 origin main:main 
          # Report metrics
          echo "## Metrics" >> report.md
          git fetch --prune
          dvc metrics diff main --md >> report.md
          # Publish confusion matrix diff
          #echo "## Plots" >> report.md
          #echo "### Class confusions" >> report.md
          dvc plots diff --target predicted_vs_actual.csv --template confusion -x actual -y predicted --show-vega main > vega.json
          vl2png vega.json -s 1.5 > confusion_plot.png
          echo "![](./confusion_plot.png)" >> report.md
          cml comment create report.md
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
